name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            name: MacOS 14
          - os: macos-15
            name: MacOS 15

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Install Prerequisites
      run: |
        brew update
        brew install icu4c libdeflate zstd argon2
    - name: Set Library Path
      run: echo "DYLD_LIBRARY_PATH=/opt/homebrew/lib:\$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
    - name: Build
      run: ./publish.cmd Release
    - name: Migration Changes
      run: git diff --exit-code ./**/Migrations/*.v*.json
    - name: Test
      run: dotnet test --no-restore

  build-linux:
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
      options: --security-opt seccomp=unconfined
    name: Build (${{ matrix.name }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: ubuntu:noble
            name: Ubuntu 24
            packageManager: apt
          - container: ubuntu:jammy
            name: Ubuntu 22
            packageManager: apt
          - container: debian:trixie
            name: Debian 13
            packageManager: apt
          - container: debian:bookworm
            name: Debian 12
            packageManager: apt
          - container: fedora:42
            name: Fedora 42
            packageManager: dnf
          - container: quay.io/centos/centos:stream9
            name: CentOS 9 Stream
            packageManager: dnf

    steps:
      - name: Enable EPEL and CRB for CentOS
        run: |
          dnf upgrade --refresh -y
          dnf install -y epel-release epel-next-release
          dnf config-manager --set-enabled crb
        if: ${{ startsWith(matrix.name, 'CentOS') }}
      - name: Install Prerequisites using dnf
        run: dnf makecache --refresh && dnf install -y findutils libicu libdeflate-devel zstd libargon2-devel liburing-devel
        if: ${{ matrix.packageManager == 'dnf' }}
      - name: Install Prerequisites using apt
        run: apt-get update -y && apt-get install -y curl libicu-dev libdeflate-dev zstd libargon2-dev tzdata liburing-dev
        if: ${{ matrix.packageManager == 'apt' }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Build
        run: ./publish.cmd Release
      - name: Test
        run: dotnet test --no-restore
